# Generated by Django 2.2.6 on 2020-03-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200323_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='works_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='y_o_p',
        ),
    ]
