# Generated by Django 2.2.6 on 2020-03-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200323_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='destination',
            new_name='designation',
        ),
    ]
